services:
  proxy-service:
    image: traefik:v2.9
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    networks:
      - vicchi-backend
    command:
      - --configFile=/etc/traefik/traefik.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOST:?Site host not defined}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls.certresolver=reverse-proxy
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/users
      - traefik.http.routers.eurotechnews.rule=Host(`www.eurotechnews.net`) || Host(`eurotechnews.net`)
      - traefik.http.routers.eurotechnews.service=noop@internal
      - traefik.http.routers.eurotechnews.middlewares=eurotechRedirect@file
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL:?CloudFlare email not defined}
      - CF_API_KEY=${CLOUDFLARE_API_KEY:?CloudFlare API key not defined}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data-stores/proxy/acme:/etc/acme
      - ./etc/traefik/dynamic:/dynamic
      - ./etc/traefik/users:/etc/traefik/users
      - ./etc/traefik/static/traefik.yml:/etc/traefik/traefik.yml

  whoami:
    image: containous/whoami:latest
    networks:
      - vicchi-backend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`www.eurotechnews.net`) || Host(`eurotechnews.net`)

  portainer-agent:
    image: portainer/agent:2.16.2
    ports:
      - 9001:9001
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - vicchi-backend

networks:
  vicchi-backend:
    external: true
