all:
  children:
    cloud:
      hosts:
        ssh.vaguelyrudeplacesmap.com:
          traefik_host: traefik.vaguelyrudeplacesmap.com
        web.vicchi.org:
          traefik_host: traefik.vicchi.org
  vars:
    ansible_user: ubuntu
    deploy_root: /var/www
    deploy_dir: reverse-proxy
    datastore_dir: data-stores
    deploy_user: ubuntu
    deploy_group: ubuntu
    traefik_network: vicchi-backend
    traefik_version: v2.9
    portainer_version: 2.16.2
    compose_project: reverse-proxy
