api:
  dashboard: true
  insecure: false

log:
  level: DEBUG

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false
    
  file:
    filename: /dynamic/traefik.yml
    watch: true

certificatesResolvers:
  reverse-proxy:
    acme:
      email: gary@vicchi.org
      storage: /etc/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

